platform:
  - x64
  # - x86

environment:
  DVersion: stable

  matrix:
    - d: dmd
    - d: ldc

init:
  - ps: |
      if ($env:PLATFORM -eq 'x86')
      {
        $env:arch = 'x86'
        $env:vcvarsall_arg = 'x86'
      }
      else
      {
        $env:arch = 'x86_64'
        $env:vcvarsall_arg = 'x86_amd64'
      }

install:
  - ps: git submodule -q update --init --recursive
  - ps: tools/install_dc.ps1

build_script:
  - echo dummy build script - dont remove me

before_test:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" %vcvarsall_arg%'

test_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true')
      {
        tools/build_release.ps1
      }
      else
      {
        dub test --verror --arch=$env:arch --compiler=$env:DC
      }

artifacts:
  - path: dlp*.7z

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: YuE5X5DFwdA7qB+OFY93l7sCWVBQ77cqKSsAtAoTrK9rMiJogtd4dK0hAh1kOmbk
  artifact: /dlp.+\.7z/
  draft: true
  on:
    appveyor_repo_tag: true
    d: ldc
